FROM python:3.8.3-alpine

RUN mkdir -p /app/log

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY functions/* ./

LABEL maintainer="Manuel Dorante <mdorante10@gmail.com>" \
    version="1.0.0"

CMD ["python", "follow_back.py"]